### ISSUE TITLE
Trying to get property X of non-object each mailable, even though these work when running in the app

### ISSUE THREAD

**Issue by lstables** [Qoraiche/laravel-mail-editor#140] opened 2020-12-10 15:31 UTC
I have just installed the package in the hope we can use this, but looks like we can't.

Every mailable that as something on it, (shown below) doesn't work

<img width="655" alt="Screenshot 2020-12-10 at 15 28 27" src="https://user-images.githubusercontent.com/1168291/101792393-90c60c00-3afc-11eb-9cb5-8fa7026c929e.png">

<img width="782" alt="Screenshot 2020-12-10 at 15 28 36" src="https://user-images.githubusercontent.com/1168291/101792409-94599300-3afc-11eb-9cb8-c8a9e4fd7ba9.png">

When having a constructor and passing info down even if it's queued or not the mailable doesn't render, I've found this with a few of my mailables, however these work as normal when sending and queueing up.

**Laravel Application**: 7

**Maileclipse package version**: 2.2

**Screenshots**

**Comment by ReeceM** [comment] 2020-12-10 15:38
Hi @lstables, thank you for raising this. 

I see that it is version 2, do you happen to know the patch version? Is it the latest v2.2.2?

With regards the queuing part of the mailable, that wouldn't be the worry as the values passed to the mail are mocked via separate object class.

**Comment by lstables** [comment] 2020-12-10 15:39
@ReeceM Hi, So would I need v2.2.2?

**Comment by ReeceM** [comment] 2020-12-10 15:40
Also, would you be able to share a stack trace on the side of the ignition error?

**Comment by lstables** [comment] 2020-12-10 15:40
As I followed the branch stating composer require qoraiche/laravel-mail-editor:^2.2 that's what I did but seems what ever is passed fails.

**Comment by ReeceM** [comment] 2020-12-10 15:41
> @ReeceM Hi, So would I need v2.2.2?

@lstables I recall there was a version in v2 that was failing and not sure what one it was off the top of my head, if possible, could you see if you have the latest version?

**Comment by lstables** [comment] 2020-12-10 15:41
Yeah it was v2.2.2 just re-installed again to get a stack trace

**Comment by lstables** [comment] 2020-12-10 15:43
<img width="1235" alt="Screenshot 2020-12-10 at 15 42 41" src="https://user-images.githubusercontent.com/1168291/101794027-59f0f580-3afe-11eb-95f1-8526c639c25c.png">

This is another mailable I have again not working as expected, so a little unsure as to why.

**Comment by ReeceM** [comment] 2020-12-10 15:43
> As I followed the branch stating composer require qoraiche/laravel-mail-editor:^2.2 that's what I did but seems what ever is passed fails.

Okay, then it should be the latest version that is in your project.

I will see if I can reproduce the error just now, I will be busy for a bit longer with work.

**Comment by lstables** [comment] 2020-12-10 15:44
@ReeceM Thank you, if you could find out why that would be awesome. I'm using Laravel Framework 7.30.0

**Comment by ReeceM** [comment] 2020-12-10 20:44
Hey there, just so you know I was able to reproduce the error on my end \:)

I have an idea as to why it is failing and should be able to get a PR through to work as this seems to be an edge case or regression.

**Comment by lstables** [comment] 2020-12-10 20:46
@ReeceM Great, how long will that take out of interest to get merged etc. Also what is it, where/what is the problem?

:)

**Comment by ReeceM** [comment] 2020-12-10 21:02
@lstables it seems to be what I thought it was, it has to do with the class that creates a dynamic mocking object that builds on itself with each call.

When building the mailable the constructor args are mocked or created, if they normal types, `string, int, float, bool` they get a static default. 

Basically, to provide dumb object resolution for calls to things like `$this->tenancy->amount_paying` is not type hinted, the class builds up those calls and creates the object. Right now it is just returning the name of the constructor property

Unfortunately, I think there was a point where I changed something that made that bit not work. 


With regards a patch release, I will have to see how long it will get to sort out a fix, I just want to make sure I sort it right though, are you in a rush to get it?


if so, in the file `vendor\qoraiche\laravel-mail-editor\src\MailEclipse.php@getMissingParams` lines 671 - 674 
```php
if (is_null($reflection)) {
            return null;
            // return $arg;
}
```

Make this if statement return null.

**Comment by ReeceM** [comment] 2020-12-10 21:03
With regards the fix, just want to make sure it isn't that, but just note the fix above 👆 will get wiped if deployed

**Comment by lstables** [comment] 2020-12-10 21:07
No major rush as such a week or two won't hurt I guess. I won't do any edits locally as as you say it will be overridden once the fix is deployed.

I thank you for taking the time to look at this and hopefully fix it, great work my friend. :)

**Comment by lstables** [comment] 2020-12-10 21:11
I can confirm that works, to some degree.

<img width="947" alt="Screenshot 2020-12-10 at 21 10 06" src="https://user-images.githubusercontent.com/1168291/101830246-2200a700-3b2c-11eb-8979-2e8860d3bf64.png">

However as you can see above when trying to edit a mailable the same sort of thing is happening. Hopefully this is what you are referring to by testing and checking it works.

**Comment by ReeceM** [comment] 2020-12-10 21:13
> I can confirm that works, to some degree.
> 
> <img alt="Screenshot 2020-12-10 at 21 10 06" width="947" src="https://user-images.githubusercontent.com/1168291/101830246-2200a700-3b2c-11eb-8979-2e8860d3bf64.png">
> 
> However as you can see above when trying to edit a mailable the same sort of thing is happening. Hopefully this is what you are referring to by testing and checking it works.

Yeah, that is the kind of thing I just want to make sure isn't happening. Just to check, are there any type hints for that value? Like a model class or another class type?

**Comment by lstables** [comment] 2020-12-10 21:14
Just in the constructor vars are passed in.

**Comment by lstables** [comment] 2020-12-10 21:16
Which are usually just arrays sorry or a collection.

**Comment by ReeceM** [comment] 2020-12-10 21:19
Cool, that helps. The Mocked class would handle those, collections or arrays. As the preview part doesn't really know the actual data you want available.

**Comment by ReeceM** [comment] 2020-12-10 21:20
Yeah, bit of a lol, slap myself moment. Looks like I patched it on v3 but didn't port the fix back into this version. Although it should have been.

**Comment by lstables** [comment] 2020-12-10 21:22
Haha, happens to us all buddy. Any chance if porting it back then if all works on v3

**Comment by ReeceM** [comment] 2020-12-10 21:22
### Version 3
https://github.com/Qoraiche/laravel-mail-editor/blob/0598e658239b3156365fe49b3a6774596842be63/src/MailEclipse.php#L716-L746

### Version 2
https://github.com/Qoraiche/laravel-mail-editor/blob/4c9bc96e5899faaf1a60c7c4d55ec0779cf474d9/src/MailEclipse.php#L657-L683


Both very different and I think for a very good reason 🤦 



> Haha, happens to us all buddy. Any chance if porting it back then if all works on v3

Yeah, I am going to do that kinda now or so, and see if that works

**Comment by lstables** [comment] 2020-12-10 21:24
Awesome, if it does and you can release an update i'll pull that in with composer update 😉👍🏻

**Comment by ReeceM** [comment] 2020-12-10 21:27
<img width="525" alt="Screen Shot 2020-12-10 at 23 26 17" src="https://user-images.githubusercontent.com/2767904/101831798-22ef0400-3b3f-11eb-80e8-398e00fed689.png">
<img width="605" alt="Screen Shot 2020-12-10 at 23 26 12" src="https://user-images.githubusercontent.com/2767904/101831803-25e9f480-3b3f-11eb-8dd6-0da25cd1b71c.png">


Works as it should do.

**Comment by lstables** [comment] 2020-12-10 21:29
Sweet, is that from v3? 
Will you now be able to update v2.2.2 to 2.2.3?

**Comment by ReeceM** [comment] 2020-12-10 21:34
> Sweet, is that from v3?
> Will you now be able to update v2.2.2 to 2.2.3?

- Yeah, thats the v3 stuff working

- The version will be v2.2.3, so a composer update should do 👍

**Comment by lstables** [comment] 2020-12-10 21:37
@ReeceM great, so can composer update now?

**Comment by ReeceM** [comment] 2020-12-10 21:39
> @ReeceM great, so can composer update now?

Not at the moment, just opened the PR \:)

**Comment by lstables** [comment] 2020-12-10 21:40
Ah, yeah so I see, thank you. @ me when you feel I can update composer if you would please. 

Once again a massive thank you for sorting this out.

**Comment by ReeceM** [comment] 2020-12-10 21:46
@lstables you should be able to give it a whirl now 👍  :)

https://github.com/Qoraiche/laravel-mail-editor/releases/tag/v2.2.3

**Comment by lstables** [comment] 2020-12-10 21:50
Great, will try it out now. Thanks dude

**Comment by lstables** [comment] 2020-12-10 21:52
<img width="1235" alt="Screenshot 2020-12-10 at 21 51 55" src="https://user-images.githubusercontent.com/1168291/101834193-eec11680-3b31-11eb-882a-52e8f5d3fb58.png">

Not sure if it's me, but get this now.

**Comment by ReeceM** [comment] 2020-12-10 21:57
Yeah, that ain't your fault. I added a new typo.

**Comment by lstables** [comment] 2020-12-10 21:58
Whoops! 😅  No worries, glad you are sorting tbh :)

**Comment by ReeceM** [comment] 2020-12-10 22:01
Could you just do the for me: `composer require qoraiche/laravel-mail-editor:dev-fix/issue-140-variable-assignment`

Then if it works I will tag the correct version then you can do: `composer require qoraiche/laravel-mail-editor:v2.2` again

**Comment by lstables** [comment] 2020-12-10 22:02
Yep, all working buddy. Awesome stuff. Thank you and well done.

**Comment by lstables** [comment] 2020-12-10 22:06
Back to 2.2.3 then I guess now?

**Comment by ReeceM** [comment] 2020-12-10 22:06
So version 2.2.4 should have it all sorted, I will close this issue in a bit, please re-open it if you have issues again.

**Comment by lstables** [comment] 2020-12-10 22:07
Ah ok, cool.

Thank you once again for swiftly sorting this. Much appreciated.

**Comment by lstables** [comment] 2020-12-10 22:09
Hmm, sorry getting `qoraiche/laravel-mail-editor v2.2.4 requires illuminate/support ^8.0`now think I'm still on `7`

**Comment by ReeceM** [comment] 2020-12-10 22:11
> Hmm, sorry getting `qoraiche/laravel-mail-editor v2.2.4 requires illuminate/support ^8.0`now think I'm still on `7`

That shouldn't be ❗. Not sure why that is like that then. It was on the v2.x branch. Sorry

**Comment by lstables** [comment] 2020-12-10 22:14
Don't understand why it worked on `dev-fix/issue-140-variable-assignment` but since trying composer update again it's now not. :(

**Comment by ReeceM** [comment] 2020-12-10 22:14
Flip, I've seen what I did...

There should be the option for gifs here...

**Comment by ReeceM** [comment] 2020-12-10 22:19
@lstables this should be resolved now.

Packagist reports the correct dependancies

**Comment by lstables** [comment] 2020-12-10 22:20
Sure is. awesome work once again my friend. Thank you kindly.

**Comment by ReeceM** [comment] 2020-12-10 22:22
Awesome, please re-open if there is something that was missed \:)

**Closed by ReeceM** 2020-12-10 22:22 UTC
Labels: V2, WIP, bug
