### ISSUE TITLE
Trying to get property 'fullname' of non-object 

### ISSUE THREAD

**Issue by 4unkur** [Qoraiche/laravel-mail-editor#63] opened 2019-12-16 09:04 UTC
I have seen that similar issues have been already submitted & resolved, but I was not able to find a clear explanation what I have to do in order to fix this issue. I have MailEclipse version 1.3 installed  
There is a `ProductCreated` mailable & `product-created.blade.php` markdown template. In that template file I have the following line:
```
New product "{{ $product->title }}" was created by user: {{ $product->user->fullname }}
```

Mailable class:  
```php
class ProductCreated extends Mailable
{
    use Queueable, SerializesModels;
    /**
     * @var User
     */
    public $user;
    /**
     * @var Product
     */
    public $product;

    /**
     * Create a new message instance.
     *
     * @param User $user
     * @param Product $product
     */
    public function __construct(User $user, Product $product)
    {
        $this->user = $user;
        $this->product = $product;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->markdown('emails.product-created');
    }
}
```

Please assist. Thanks.

**Comment by LorenzoSapora** [comment] 2019-12-16 21:11
Commenting so I can follow this, and also because I'm facing a similar error, but

```text
"Trying to get property 'email' of non-object"
```

from

```php
// vendor/laravel/framework/src/Illuminate/Mail/Mailable.php

    protected function setAddress($address, $name = null, $property = 'to')
    {
        foreach ($this->addressesToArray($address, $name) as $recipient) {
            $recipient = $this->normalizeRecipient($recipient);
 
            $this->{$property}[] = [
                'name' => $recipient->name ?? null,
                'address' => $recipient->email,
            ];
        }
 
        return $this;
    }
 
```

Fresh install `laravel-mail-editor 1.3` into a development environment of `laravel 5.8.*`

**Comment by ReeceM** [comment] 2020-05-24 21:10
Hi @4unkur and @LorenzoSapora, are you still experiencing issues?

**Comment by KhoaDuongUQ** [comment] 2020-06-24 01:44
The whole package is unusable with this bug. Is there anyone knows how to this?

**Comment by ReeceM** [comment] 2020-06-24 07:59
Hi @KhoaDuongUQ, the bug from what I have traced down is the fact that the relations are not loaded up.

So what you could do is remove the `Model` and leave it as an undefined object type and then the variable will be given a dynamic object, this would be a temporary solution to use when you are testing the mails in the preview pane.

But seems that this is still and issue and you are actively experiencing it, can you share details of the class that this affected ? Like if it is a relation that you are calling that is giving the error? 👍

**Comment by s72817** [comment] 2020-09-15 13:56
Hi, same issue like @LorenzoSapora "Trying to get property 'email' of non-object". 
Laravel: 6.18.40 no fresh install -> is an existing project

There is actually no way to call the dashboard of Mail Editor.

**Comment by ReeceM** [comment] 2020-09-15 14:43
Hi @s72817 thank you for your input.

Is the class or object that the email value is being retrieved from a Model or a different class?

If you would be able to share some details that can help to see what is the main cause of this

**Comment by s72817** [comment] 2020-09-15 15:00
Hi @ReeceM thanks for your quick reply!!
If found the issue... in my Mail Folder there are some existing Mailable and one of them trigger it.
It works, if I comment out all of the existing Mailable. Actually I'm on the way to found my issue :)

**Comment by ReeceM** [comment] 2020-09-15 15:44
@s72817 so the reason why the issue may be there is that MailEclipse generates Model classes or provides variables to the mailable so that you can preview it.

There are two classes that are passed to the mailable, the one is an Eloquent `Model` if it is type hinted, and then if the other is not it is a `Mocked` class, this handles dynamic object calls. 

So if there is a different type of class, it may be that it isn't instantiated to the correct value or that the Model class doesn't have the right things. 

So if you are able to when you find which Mailable is causing it, you should be able to share the `__construct()` parameters. :)

Also, another thing that would be useful for your error would be the error log for when it happens, this would help to see which area it is coming from. 

From my reply to another user on this issue, the main thing is when it is called via a relationship, then it doesn't load unfortunately, I am trying to figure what a practical way is to hydrate any relationship models attached to the parent model

**Comment by BoGnY** [comment] 2021-03-05 10:09
same problem :cry:

**Comment by ReeceM** [comment] 2021-03-05 13:58
> same problem 😢

Hi @BoGnY sorry that you are having issues, may I ask if the value that you are calling is through a relation on the model or is it a normal class?

**Comment by BoGnY** [comment] 2021-03-05 15:21
[**@ReeceM**](https://github.com/ReeceM) commented on [5 mar 2021, 14:58 CET](https://github.com/Qoraiche/laravel-mail-editor/issues/63#issuecomment-791435774 "2021-03-05T13:58:21Z - Replied by Github Reply Comments"):
> > same problem ![cry](https://github.githubassets.com/images/icons/emoji/unicode/1f622.png)
> 
> Hi [@BoGnY](https://github.com/BoGnY) sorry that you are having issues, may I ask if the value that you are calling is through a relation on the model or is it a normal class?

Hi @ReeceM the problem is on property of relation on the model.
This is one of `Mailable` with problem:
```php
namespace App\Mail;

use App\Models\Subscription;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class SendSubscriptionPaymentReminder extends Mailable implements ShouldQueue
{
    use Queueable;
    use SerializesModels;

    /** @var \App\Models\Subscription */
    public $subscription;

    /** @var string */
    public $url;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct(Subscription $subscription, string $url)
    {
        $this->subscription = $subscription;
        $this->url = $url;
    }

    /**
     * Build the message.
     */
    public function build(): self
    {
        $this->subject(trans('mail.subscription_payment_reminder.title', ['plan_name' => $this->subscription->plan->name])); // <-- HERE THE ERROR: Attempt to read property "name" on null

        return $this->view('mail.subscription-payment-reminder')
            ->with([
                'subscription' => $this->subscription,
                'url' => $this->url,
            ]);
    }
}
```

I'm using MailEclipse v2.2.4 with Laravel 7.30.4

**Comment by ReeceM** [comment] 2021-03-05 15:53
@BoGnY, alright, so I see that it is also from a relationship that you are calling `name` property. 

I have been trying to wrap my head around a sensible fix for this. This would make it that all the possible relations for a model need to be faked. But I am not sure the depth that it would need to go so as to be practical or sensible. 

It could be something that is defined in the config file, like `max_depth` kind of thing.

For any of the other mailable that you have there, is there anything that is deeper than a first / second level relationship call?

**Comment by BoGnY** [comment] 2021-03-05 18:02
No @ReeceM , I have at most 2 levels of depth in relationships :+1: 
Defining it in the configuration file seems to me the correct idea to avoid problems with larger applications

**Comment by wawanneutron** [comment] 2021-06-18 15:28
same problem 😢.
Any solution for this? I am also getting the same

**Comment by ReeceM** [comment] 2021-06-21 21:18
📢 Just to provide some feedback. 📢 

I have had some time to test out the idea I had to be able to detect/guess relations that are on models, as this is where the issue comes in, and to try and initialize those relations as well.

Through testing, the initial method is lending itself to limiting the total number of relations searched to at most 2, this is because to actual do it further would result in longer response time.

What will be available I am thinking then is this:

1. At most 2 levels deep reaction testing
2. No more than one model hydrated per relation,
    -  possibly 2 from a config setting for things like loops `(e.g. comments)`
3. If it can't hydrate the model because there isn't a factory, it will load the Mocker object class to provide dynamic response.

The reason for number 3 is the case where someone might have a relation, but because the package uses factories to create a new model instance, if it isn't there usually it provides the blank instance. 

If someone is calling a relation like below:

```
$user->account->plan->name
^      ^        ^      ^
|      |        |       \ ------------------- adds to the headache, as plan is `null`
|      |        \ -------------------------- where the issue happens, the relation hasn't been loaded
|       \ ------------------------------------- this is still okay, as the Model::class returns null
\--------------------------------------------- this is okay
```

Then with the changes, hopefully the account will be a valid relation, the plan will also be, but name will have to be based on the plan. 

At that point, my earlier comment of allowing a config to be set for the number of relations would have to come into effect for certain use cases. https://github.com/Qoraiche/laravel-mail-editor/issues/63#issuecomment-791507222

Please feel free to share a GH reaction to give some feedback 👍

**Comment by ReeceM** [comment] 2021-06-28 06:26
Hi all that have commented on the issue or had this issue, I would like to see if those who had the issue are able to make use of the branch version to test in their Laravel apps. 

You can spin up a new Laravel app or try it in one already, you can change the version to `dev-fix/issue-63-loading-relations` in the composer file and run `composer update`, it should require the branch and not the tagged version, obviously, this is just to test and confirm that the PR #157 does indeed fix the issue that some have faced.

You can share your issues back in here should the PR add issue for you.

**Closed** 2021-07-16 13:25 UTC
Labels: Good Issue, Reviewed, V2, V3, WIP, bug

**Comment by ReeceM** [comment] 2021-07-16 21:05
Hi all, we are happy to note that the versions [3.4](https://github.com/Qoraiche/laravel-mail-editor/releases/tag/v3.4.0) and [2.3](https://github.com/Qoraiche/laravel-mail-editor/releases/tag/v2.3.0) each have a fix for this issue.

Thank you all for being patient for the fix and also for initially raising the issue and providing more information about it so that it could be sorted out.

Please feel free to open a new issue should there be bugs for it.
