### ISSUE TITLE
View [createmailable] not found.

### ISSUE THREAD

**Issue by armelgeek** [Qoraiche/laravel-mail-editor#64] opened 2020-01-02 04:26 UTC
Someone can help my for this error View [createmailable] not found.

**Comment by maximiliandoerner** [comment] 2020-02-11 11:59
got the same error, any way you could fix this?

**Comment by ReeceM** [comment] 2020-12-11 18:42
This issue I believe would have been resolved by the PR #135, I think that would have been the cause of this. As there wasn't any further info provided, it will be closed

**Closed by ReeceM** 2020-12-11 18:42 UTC
Labels: bug
